import './globals.css'
import React from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
      <body className="flex flex-col min-h-screen">
      
        <main className="flex-grow">{children}</main>
       
      </body>
    
  );
}